/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 *
 * @author josep
 */
public class OlvideDatos extends javax.swing.JFrame {

    /**
     * Creates new form OlvideDatos
     */
    public OlvideDatos() {
        initComponents();
        setLocationRelativeTo(null); // para centrar la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        BTNSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        TXTDni = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BTNExisteDni = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTAREAResultado = new javax.swing.JTextArea();
        BTNRegresar = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ecg_80px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("SystemAlert");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Registrar Nuevo Usuario");

        BTNSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_exit_sign_64px.png"))); // NOI18N
        BTNSalir.setText("Regresar");
        BTNSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNSalirMouseClicked(evt);
            }
        });
        BTNSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSalirActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ecg_80px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 102));
        jLabel5.setText("SystemAlert");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Recuperar Datos");

        jLabel7.setText("Dni:");

        BTNExisteDni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_client_48px.png"))); // NOI18N
        BTNExisteDni.setText("¿Existe DNI?");
        BTNExisteDni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNExisteDniMouseClicked(evt);
            }
        });

        TXTAREAResultado.setColumns(20);
        TXTAREAResultado.setRows(5);
        jScrollPane1.setViewportView(TXTAREAResultado);

        BTNRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_exit_sign_64px.png"))); // NOI18N
        BTNRegresar.setText("Regresar");
        BTNRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNRegresarMouseClicked(evt);
            }
        });
        BTNRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(TXTDni, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BTNExisteDni))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(BTNRegresar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TXTDni, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNExisteDni)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(BTNRegresar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNExisteDniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNExisteDniMouseClicked
        try {
            String dni, leerLinea;
            int conta = 0;
            dni = TXTDni.getText();

            BufferedReader leerTXT = new BufferedReader(new FileReader("Usuario.txt"));

            System.out.println("-------------------------------------------------------------------------------------");
            System.out.println("DNI      Nombre       ApePaterno     ApeMaterno      edad      Usuario    Contraseña ");
            System.out.println("-------------------------------------------------------------------------------------");

            while ((leerLinea = leerTXT.readLine()) != null) {
                StringTokenizer st = new StringTokenizer(leerLinea, ",");
                if (leerLinea.contains(dni)) {
                    conta++;
                    if (conta > 0) {
                        JOptionPane.showMessageDialog(null, "Datos Encontrados", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                        TXTAREAResultado.setText("Dni: " + st.nextToken() + 
                                                 "\n Nombre: " + st.nextToken() +
                                                 "\n Apellido Paterno: " + st.nextToken() +
                                                 "\n Apellido Materno: " + st.nextToken() +
                                                 "\n Edad: "+ st.nextToken() + 
                                                 "\n Usuario:" + st.nextToken() + 
                                                 "\n Contraseña:" + st.nextToken());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Datos NO Encontrados", "Mensaje", JOptionPane.WARNING_MESSAGE);
                }

            }
        } catch (FileNotFoundException e) {
            System.out.println(e.getMessage());

        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_BTNExisteDniMouseClicked

    private void BTNSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNSalirMouseClicked

        int BotonDialogo = JOptionPane.YES_NO_OPTION;
        int dialogoResultado = JOptionPane.showConfirmDialog(this, "¿Desea salir del regsitro?", "Mensaje", BotonDialogo);
        if (dialogoResultado == 0) {
            this.setVisible(false);
            Login inicio = new Login();
            inicio.setVisible(true);
        } else {
            System.out.println(":')'");
        }

    }//GEN-LAST:event_BTNSalirMouseClicked

    private void BTNSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNSalirActionPerformed

    private void BTNRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNRegresarMouseClicked

        int BotonDialogo = JOptionPane.YES_NO_OPTION;
        int dialogoResultado = JOptionPane.showConfirmDialog(this, "¿Desea salir del regsitro?", "Mensaje", BotonDialogo);
        if (dialogoResultado == 0) {
            this.setVisible(false);
            Login inicio = new Login();
            inicio.setVisible(true);
        } else {
            System.out.println(":')'");
        }

    }//GEN-LAST:event_BTNRegresarMouseClicked

    private void BTNRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OlvideDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OlvideDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OlvideDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OlvideDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OlvideDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNExisteDni;
    private javax.swing.JButton BTNRegresar;
    private javax.swing.JButton BTNSalir;
    private javax.swing.JTextArea TXTAREAResultado;
    private javax.swing.JTextField TXTDni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
